CREATE TABLE mail_accounts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL,
 imap_host VARCHAR(255), imap_port INT NOT NULL, imap_tls VARCHAR(20),
 imap_username VARCHAR(255), imap_secret VARCHAR(4096),
 smtp_host VARCHAR(255), smtp_port INT NOT NULL, smtp_tls VARCHAR(20),
 smtp_username VARCHAR(255), smtp_secret VARCHAR(4096),
 enabled BOOLEAN NOT NULL, history_days INT NOT NULL, uid_validity BIGINT,
 last_uid BIGINT NOT NULL, received_after TIMESTAMP WITH TIME ZONE,
 last_checked TIMESTAMP WITH TIME ZONE, last_error VARCHAR(512), reset_required BOOLEAN NOT NULL
);
CREATE TABLE forward_rules (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL,
 enabled BOOLEAN NOT NULL, subject_mode VARCHAR(20), subject_pattern VARCHAR(1000), ignore_case BOOLEAN NOT NULL
);
CREATE TABLE rule_accounts (rule_id BIGINT REFERENCES forward_rules(id), account_id BIGINT REFERENCES mail_accounts(id), PRIMARY KEY(rule_id,account_id));
CREATE TABLE rule_recipients (rule_id BIGINT REFERENCES forward_rules(id), address VARCHAR(255), PRIMARY KEY(rule_id,address));
CREATE TABLE rule_targets (rule_id BIGINT REFERENCES forward_rules(id), address VARCHAR(255), PRIMARY KEY(rule_id,address));
CREATE TABLE received_mail (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_id BIGINT NOT NULL REFERENCES mail_accounts(id),
 folder_name VARCHAR(255) NOT NULL, uid_validity BIGINT NOT NULL, imap_uid BIGINT NOT NULL,
 subject VARCHAR(2048), sender VARCHAR(2048), recipients VARCHAR(4000), received_at TIMESTAMP WITH TIME ZONE,
 processed_at TIMESTAMP WITH TIME ZONE, outcome VARCHAR(255), payload_name VARCHAR(255), matched_rules VARCHAR(2048),
 CONSTRAINT unique_source UNIQUE(account_id,folder_name,uid_validity,imap_uid)
);
CREATE TABLE deliveries (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, mail_id BIGINT NOT NULL REFERENCES received_mail(id),
 account_id BIGINT NOT NULL REFERENCES mail_accounts(id), target VARCHAR(255) NOT NULL, status VARCHAR(20),
 attempts INT NOT NULL, retry_count INT NOT NULL, next_attempt TIMESTAMP WITH TIME ZONE, updated_at TIMESTAMP WITH TIME ZONE,
 last_error VARCHAR(512), CONSTRAINT unique_target UNIQUE(mail_id,target)
);
CREATE INDEX delivery_due ON deliveries(status,next_attempt);
CREATE INDEX received_date ON received_mail(processed_at);
CREATE TABLE delivery_attempts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, delivery_id BIGINT NOT NULL REFERENCES deliveries(id),
 attempted_at TIMESTAMP WITH TIME ZONE, outcome VARCHAR(255), detail VARCHAR(512)
);
