CREATE TABLE share_pages (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title VARCHAR(200) NOT NULL,
 token_hash VARCHAR(64) NOT NULL,
 account_id BIGINT REFERENCES mail_accounts(id),
 subject_keyword VARCHAR(1000) NOT NULL,
 enabled BOOLEAN NOT NULL,
 expires_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 CONSTRAINT unique_share_token UNIQUE(token_hash)
);
CREATE INDEX share_page_status ON share_pages(enabled, expires_at);
